### ISSUE TITLE
Repositório Vazio !?

### ISSUE THREAD

**Issue by DanielP33** [rlcosta177/wazuh-offline-installation#1]
@rlcosta177  Notei que o repositório está vazio. Confirmo que estou a atualizar à cinco horas. Em geral, é uma boa prática garantir que o repositório tenha uma estrutura mínima de arquivos ou um README inicial para fornecer contexto e orientação. Isso ajuda a evitar confusões e melhora a colaboração. Obrigado pela compreensão!

**Comment by rlcosta177** [comment]
@DanielP33 Infelizmente, a instalação de wazuh em servidores isolados vai demorar alguns dias a ser completo, pois a ferramenta näo quer cooperar, assim se tornando numa ferramenta absolutamente proterva.

Agradeço a sua preocupação com o estado deste projeto, e acredite que o mesmo não ficará neste estado, obrigado pelo feedback e cumprimentos! 

Wazuh to me rn:
![a60d578bb1bc25ce72969fba7958bdf6](https://github.com/user-attachments/assets/69771038-537f-4b23-9b33-4792e53ca5cf)
